site_name: Desafio de DevOps Engineer - EMD
repo_url: https://github.com/thiago-felipe-99/emd-desafio-devops
repo_name: thiago-felipe-99/emd-desafio-devops
edit_uri: tree/main/docs
site_url: https://thiago-felipe-99.github.io/emd-desafio-devops/

theme:
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  name: material
  language: pt-BR
