title: Desafio de DevOps Engineer - EMD
email: thiago.felipe@poli.ufrj.br
baseurl: "/emd-desafio-devops"
domain: thiago-felipe-99.github.io
url: https://thiago-felipe-99.github.io
github_username:  thiago-felipe-99

theme: minima
plugins:
  - jekyll-feed

lsi: false
safe: true
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
