name: Create Weekly Tag

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'  # Run every Sunday at midnight (UTC)

jobs:
  create-tag:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Get current date
      id: date
      run: echo "::set-output name=week::$(date +'%Y-%U')"

    - name: Check for commits this week
      id: check-commits
      run: |
        current_week="$(echo ${{ steps.date.outputs.week }} | tr '-' '/')"
        week_commits="$(git log --since='1 week ago' --format='%cd' --date=iso | grep $current_week | wc -l)"
        echo "::set-output name=has_commits::$(if [ $week_commits -gt 0 ]; then echo 'true'; else echo 'false'; fi)"

    - name: Create tag
      if: ${{ steps.check-commits.outputs.has_commits == 'true' }}
      run: |
        git tag "weekly-$(echo ${{ steps.date.outputs.week }} | tr '-' '/')"
        git push origin --tags
